import { Farm, FieldZone, CropItem, LivestockAnimal, AdvisoryItem, AlertNotification, FarmTask, TimelineEvent, DiseaseScanResult, DiseaseProgressionEntry, FarmFeedPost, UserSubscription } from '@/types/schema';

export const INITIAL_FARMS: Farm[] = [
  {
    id: 'farm-1',
    ownerId: 'user-1',
    name: 'Rajasthan Green Fields',
    farmerName: 'Rajesh Kumar',
    state: 'Rajasthan',
    district: 'Jaipur',
    village: 'Sanganer',
    farmAreaAcres: 18.5,
    primaryCrop: 'Tomato',
    livestockCount: 14,
    latitude: 26.8206,
    longitude: 75.8055,
    createdAt: '2025-10-15T08:00:00Z',
    updatedAt: '2026-08-13T08:00:00Z',
  },
  {
    id: 'farm-2',
    ownerId: 'user-1',
    name: 'Jaipur Organic Farm',
    farmerName: 'Rajesh Kumar',
    state: 'Rajasthan',
    district: 'Jaipur',
    village: 'Amer',
    farmAreaAcres: 12.0,
    primaryCrop: 'Wheat',
    livestockCount: 8,
    latitude: 26.9855,
    longitude: 75.8513,
    createdAt: '2026-01-10T09:30:00Z',
    updatedAt: '2026-08-12T10:15:00Z',
  },
];

export const INITIAL_FIELDS: FieldZone[] = [
  {
    id: 'field-north',
    farmId: 'farm-1',
    name: 'North Field',
    type: 'field',
    areaAcres: 5.5,
    currentCrop: 'Tomato & Chilli',
    healthScore: 74,
    soilMoisture: 42,
    phLevel: 6.8,
    nitrogenLevel: 'Optimal',
    irrigationStatus: 'Active',
    lastScanDate: '2026-08-13T09:15:00Z',
    coordinates: { x: 5, y: 5, width: 42, height: 40 },
  },
  {
    id: 'field-south',
    farmId: 'farm-1',
    name: 'South Field',
    type: 'field',
    areaAcres: 6.0,
    currentCrop: 'Potato & Wheat',
    healthScore: 94,
    soilMoisture: 58,
    phLevel: 7.1,
    nitrogenLevel: 'Optimal',
    irrigationStatus: 'Scheduled',
    lastScanDate: '2026-08-12T16:00:00Z',
    coordinates: { x: 52, y: 5, width: 43, height: 40 },
  },
  {
    id: 'field-east',
    farmId: 'farm-1',
    name: 'East Field',
    type: 'field',
    areaAcres: 4.0,
    currentCrop: 'Onion & Mustard',
    healthScore: 88,
    soilMoisture: 50,
    phLevel: 6.9,
    nitrogenLevel: 'Low',
    irrigationStatus: 'Idle',
    lastScanDate: '2026-08-11T11:30:00Z',
    coordinates: { x: 5, y: 50, width: 42, height: 45 },
  },
  {
    id: 'zone-livestock',
    farmId: 'farm-1',
    name: 'Livestock Shed A',
    type: 'livestock',
    areaAcres: 1.5,
    healthScore: 90,
    soilMoisture: 30,
    phLevel: 7.0,
    nitrogenLevel: 'Optimal',
    irrigationStatus: 'Idle',
    lastScanDate: '2026-08-13T08:00:00Z',
    coordinates: { x: 52, y: 50, width: 22, height: 22 },
  },
  {
    id: 'zone-water',
    farmId: 'farm-1',
    name: 'Solar Borewell & Tank',
    type: 'water',
    areaAcres: 0.5,
    healthScore: 98,
    soilMoisture: 100,
    phLevel: 7.2,
    nitrogenLevel: 'Optimal',
    irrigationStatus: 'Active',
    lastScanDate: '2026-08-13T10:00:00Z',
    coordinates: { x: 78, y: 50, width: 17, height: 22 },
  },
  {
    id: 'zone-storage',
    farmId: 'farm-1',
    name: 'Grain Storage & Silo',
    type: 'storage',
    areaAcres: 1.0,
    healthScore: 95,
    soilMoisture: 12,
    phLevel: 7.0,
    nitrogenLevel: 'Optimal',
    irrigationStatus: 'Idle',
    lastScanDate: '2026-08-10T14:00:00Z',
    coordinates: { x: 52, y: 75, width: 43, height: 20 },
  },
];

export const INITIAL_CROPS: CropItem[] = [
  {
    id: 'crop-1',
    farmId: 'farm-1',
    fieldId: 'field-north',
    name: 'Tomato',
    variety: 'Pusa Ruby',
    areaAcres: 3.5,
    sowingDate: '2026-05-10',
    growthStage: 'Fruiting',
    healthScore: 74,
    diseaseRisk: 'high',
    expectedYieldKg: 4200,
    lastScanDate: '2026-08-13T09:15:00Z',
    activeCondition: 'Early Blight (Alternaria solani)',
    imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-2',
    farmId: 'farm-1',
    fieldId: 'field-south',
    name: 'Potato',
    variety: 'Kufri Jyoti',
    areaAcres: 4.0,
    sowingDate: '2026-06-01',
    growthStage: 'Vegetative',
    healthScore: 92,
    diseaseRisk: 'low',
    expectedYieldKg: 8500,
    lastScanDate: '2026-08-12T16:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-3',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Onion',
    variety: 'N-53 Red',
    areaAcres: 2.5,
    sowingDate: '2026-05-20',
    growthStage: 'Flowering',
    healthScore: 88,
    diseaseRisk: 'low',
    expectedYieldKg: 3100,
    lastScanDate: '2026-08-11T11:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-4',
    farmId: 'farm-1',
    fieldId: 'field-north',
    name: 'Chilli',
    variety: 'G-4 Green',
    areaAcres: 2.0,
    sowingDate: '2026-05-15',
    growthStage: 'Fruiting',
    healthScore: 65,
    diseaseRisk: 'high',
    expectedYieldKg: 1800,
    lastScanDate: '2026-08-10T14:45:00Z',
    activeCondition: 'Leaf Curl Virus',
    imageUrl: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-5',
    farmId: 'farm-1',
    fieldId: 'field-south',
    name: 'Wheat',
    variety: 'HD-2967',
    areaAcres: 2.0,
    sowingDate: '2026-04-10',
    growthStage: 'Harvesting',
    healthScore: 96,
    diseaseRisk: 'low',
    expectedYieldKg: 4900,
    lastScanDate: '2026-08-09T08:20:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
  },
];

export const INITIAL_PROGRESSION: DiseaseProgressionEntry[] = [
  {
    dayLabel: 'Day 1',
    date: '2026-08-01',
    affectedAreaPercent: 7,
    severity: 'low',
    healthScore: 91,
    treatmentApplied: 'None',
    weatherHumidity: 62,
    aiInterpretation: 'Initial subtle brown concentric rings detected on lower foliage.',
  },
  {
    dayLabel: 'Day 4',
    date: '2026-08-05',
    affectedAreaPercent: 12,
    severity: 'moderate',
    healthScore: 84,
    treatmentApplied: 'Neem Oil Spray (15ml/L)',
    weatherHumidity: 68,
    aiInterpretation: 'Lesions expanded into target-board pattern with yellow chlorotic halos.',
  },
  {
    dayLabel: 'Day 8',
    date: '2026-08-09',
    affectedAreaPercent: 18,
    severity: 'moderate',
    healthScore: 78,
    treatmentApplied: 'Organic Trichoderma Bio-fungicide',
    weatherHumidity: 75,
    aiInterpretation: 'Spreading upward to mid-canopy leaves following monsoon rains.',
  },
  {
    dayLabel: 'Day 12',
    date: '2026-08-13',
    affectedAreaPercent: 29,
    severity: 'high',
    healthScore: 74,
    treatmentApplied: 'Pending Copper Oxychloride Spray',
    weatherHumidity: 82,
    aiInterpretation: 'Observed affected leaf area has increased rapidly due to high ambient humidity (82%). Immediate fungicide application required.',
  },
];

export const INITIAL_LIVESTOCK: LivestockAnimal[] = [
  {
    id: 'animal-1',
    farmId: 'farm-1',
    tagNumber: 'IND-RJ-101',
    type: 'Cow',
    breed: 'Sahiwal',
    ageMonths: 36,
    weightKg: 425,
    healthScore: 92,
    riskLevel: 'low',
    lastVaccinationDate: '2026-06-15',
    nextVaccinationDue: '2026-12-15',
    lastCheckDate: '2026-08-13',
    imageUrl: 'https://images.unsplash.com/photo-1546445317-29f4545f9d52?auto=format&fit=crop&w=600&q=80',
    notes: 'High milk yield (14L/day). Calm temperament.',
  },
  {
    id: 'animal-2',
    farmId: 'farm-1',
    tagNumber: 'IND-RJ-204',
    type: 'Buffalo',
    breed: 'Murrah Water Buffalo',
    ageMonths: 48,
    weightKg: 580,
    healthScore: 84,
    riskLevel: 'medium',
    lastVaccinationDate: '2026-02-10',
    nextVaccinationDue: '2026-08-20',
    lastCheckDate: '2026-08-12',
    imageUrl: '/images/buffalo.png',
    notes: 'Foot-and-Mouth vaccination due within 7 days.',
  },
  {
    id: 'animal-3',
    farmId: 'farm-1',
    tagNumber: 'IND-RJ-309',
    type: 'Goat',
    breed: 'Barbari Goat',
    ageMonths: 18,
    weightKg: 34,
    healthScore: 95,
    riskLevel: 'low',
    lastVaccinationDate: '2026-05-01',
    nextVaccinationDue: '2026-11-01',
    lastCheckDate: '2026-08-11',
    imageUrl: '/images/goat.png',
    notes: 'Active grazing, good appetite.',
  },
  {
    id: 'animal-4',
    farmId: 'farm-1',
    tagNumber: 'IND-RJ-402',
    type: 'Sheep',
    breed: 'Marwari Sheep',
    ageMonths: 24,
    weightKg: 48,
    healthScore: 88,
    riskLevel: 'low',
    lastVaccinationDate: '2026-04-12',
    nextVaccinationDue: '2026-10-12',
    lastCheckDate: '2026-08-10',
    imageUrl: 'https://images.unsplash.com/photo-1484557052118-f32bd25b45b5?auto=format&fit=crop&w=600&q=80',
    notes: 'Wool sheared last month. Normal body condition.',
  },
  {
    id: 'animal-5',
    farmId: 'farm-1',
    tagNumber: 'IND-RJ-510',
    type: 'Chicken',
    breed: 'Kadaknath / Poultry Flock',
    ageMonths: 8,
    weightKg: 2.4,
    healthScore: 96,
    riskLevel: 'low',
    lastVaccinationDate: '2026-07-01',
    nextVaccinationDue: '2026-10-01',
    lastCheckDate: '2026-08-13',
    imageUrl: '/images/chicken.png',
    notes: 'Healthy laying hens, active coop behavior.',
  },
];

export const INITIAL_ADVISORIES: AdvisoryItem[] = [
  {
    id: 'adv-1',
    farmId: 'farm-1',
    priority: 'CRITICAL',
    category: 'Crop',
    title: 'Tomato Field Disease Progression Alert',
    reason: 'Affected leaf surface expanded from 18% to 29% over the last 4 days due to 82% ambient humidity.',
    recommendedActions: [
      'Apply Copper Oxychloride (2.5g/L water) or Mancozeb fungicide spray immediately on North Field.',
      'Prune severely infected bottom leaves and dispose of outside the farm area.',
      'Pause overhead sprinkler irrigation; switch to drip irrigation to keep canopy dry.',
    ],
    relatedCropId: 'crop-1',
    createdAt: '2026-08-13T09:20:00Z',
    status: 'active',
  },
  {
    id: 'adv-2',
    farmId: 'farm-1',
    priority: 'HIGH',
    category: 'Weather',
    title: 'High Humidity Fungal Risk Warning',
    reason: 'Weather intelligence forecasts 85% relative humidity with light scattered rainfall in Jaipur over the next 48 hours.',
    recommendedActions: [
      'Inspect Chilli crops in North Field for whitefly infestation and leaf curling.',
      'Ensure field drainage channels are clear to prevent waterlogging around roots.',
    ],
    relatedCropId: 'crop-4',
    createdAt: '2026-08-13T07:45:00Z',
    status: 'active',
  },
  {
    id: 'adv-3',
    farmId: 'farm-1',
    priority: 'MEDIUM',
    category: 'Livestock',
    title: 'FMD Vaccination Reminder for Murrah Buffalo',
    reason: 'Tag #IND-RJ-204 due for booster Foot-and-Mouth Disease vaccination by August 20.',
    recommendedActions: [
      'Schedule visit with local government veterinary doctor.',
      'Check temperature and dewlap area for swelling.',
    ],
    createdAt: '2026-08-12T14:30:00Z',
    status: 'active',
  },
];

export const INITIAL_ALERTS: AlertNotification[] = [
  {
    id: 'alt-1',
    farmId: 'farm-1',
    type: 'Disease',
    severity: 'Critical',
    title: 'Rapid Early Blight Progression',
    message: 'Tomato leaf affected area reached 29%. Action required today.',
    timestamp: '2026-08-13T09:16:00Z',
    read: false,
    sourceEvidenceId: 'crop-1',
  },
  {
    id: 'alt-2',
    farmId: 'farm-1',
    type: 'Weather',
    severity: 'Attention',
    title: 'Heavy Rain Warning (85% Humidity)',
    message: 'Scattered monsoon showers expected between 14:00 - 18:00.',
    timestamp: '2026-08-13T06:30:00Z',
    read: false,
  },
  {
    id: 'alt-3',
    farmId: 'farm-1',
    type: 'Livestock',
    severity: 'Information',
    title: 'Daily Feeding Completed',
    message: 'Livestock Shed A morning fodder delivered successfully.',
    timestamp: '2026-08-13T08:00:00Z',
    read: true,
  },
];

export const INITIAL_TASKS: FarmTask[] = [
  {
    id: 'task-1',
    farmId: 'farm-1',
    title: 'Apply Copper Fungicide Spray on Tomato Field',
    description: 'Target lower canopy in North Field to control Early Blight progression.',
    priority: 'High',
    status: 'Todo',
    dueDate: '2026-08-13',
    assignedTo: 'Farm Owner',
    relatedCropOrAnimal: 'Tomato (Pusa Ruby)',
    reason: 'Disease progression from 18% to 29%',
    createdAt: '2026-08-13T09:25:00Z',
  },
  {
    id: 'task-2',
    farmId: 'farm-1',
    title: 'Inspect Solar Water Pump Filter',
    description: 'Clean inlet mesh and record flow rate reading.',
    priority: 'Medium',
    status: 'In Progress',
    dueDate: '2026-08-13',
    assignedTo: 'Suresh Patel',
    relatedCropOrAnimal: 'Solar Borewell',
    createdAt: '2026-08-13T07:00:00Z',
  },
];

export const INITIAL_TIMELINE: TimelineEvent[] = [
  {
    id: 'time-1',
    farmId: 'farm-1',
    timestamp: '2026-08-13T09:15:00Z',
    timeLabel: '09:15 AM',
    title: 'AI Crop Scan Uploaded',
    description: 'Tomato leaf photo uploaded via mobile scanner. Early Blight detected at 94% confidence.',
    type: 'scan',
    icon: 'Camera',
    actor: 'Farm Owner',
  },
  {
    id: 'time-2',
    farmId: 'farm-1',
    timestamp: '2026-08-13T09:20:00Z',
    timeLabel: '09:20 AM',
    title: 'Critical Advisory Generated',
    description: 'AI System flagged rapid 11% disease expansion due to elevated humidity.',
    type: 'advisory',
    icon: 'AlertTriangle',
    actor: 'AgriVision AI Engine',
  },
];

export const INITIAL_FEED: FarmFeedPost[] = [
  {
    id: 'feed-1',
    farmId: 'farm-1',
    farmName: 'Rajasthan Green Fields',
    farmerName: 'Farm Owner',
    farmerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    timestamp: '2 hours ago',
    imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=800&q=80',
    category: 'Diseases',
    targetName: 'Tomato - North Field',
    description: 'Scanned lower canopy leaves today. Early Blight brown rings visible. Applying bio-fungicide this evening.',
    aiAnalysis: {
      condition: 'Early Blight (Alternaria solani)',
      confidence: 94,
      severity: 'Moderate to High',
    },
    likesCount: 12,
    commentsCount: 3,
    userLiked: true,
  },
];

export const INITIAL_SUBSCRIPTION: UserSubscription = {
  plan: 'Professional',
  status: 'active',
  scansUsedThisMonth: 18,
  scansLimit: 500,
  aiChatsUsedThisMonth: 42,
  aiChatsLimit: 2000,
  renewalDate: '2026-09-01',
};
