import {
  Farm,
  FieldZone,
  CropItem,
  LivestockAnimal,
  AdvisoryItem,
  AlertNotification,
  FarmTask,
  TimelineEvent,
  DiseaseProgressionEntry,
  FarmFeedPost,
  UserSubscription,
  MarketplaceItem,
  MandiPriceItem,
  TreatmentScheduleItem,
  CommunityPost
} from '@/types/schema';

export const INITIAL_FARMS: Farm[] = [
  {
    id: 'farm-1',
    ownerId: 'user-1',
    name: 'Rajasthan Green Fields',
    farmerName: 'Rajesh Kumar',
    state: 'Rajasthan',
    district: 'Jaipur',
    village: 'Sanganer',
    farmAreaAcres: 18.5,
    primaryCrop: 'Wheat & Mustard',
    livestockCount: 16,
    latitude: 26.8206,
    longitude: 75.8055,
    createdAt: '2025-10-15T08:00:00Z',
    updatedAt: '2026-08-14T08:00:00Z',
  },
];

export const INITIAL_FIELDS: FieldZone[] = [
  {
    id: 'field-north',
    farmId: 'farm-1',
    name: 'North Field (Grains & Pulses)',
    type: 'field',
    areaAcres: 5.5,
    currentCrop: 'Wheat & Chickpea',
    healthScore: 88,
    soilMoisture: 48,
    phLevel: 6.8,
    nitrogenLevel: 'Optimal',
    irrigationStatus: 'Active',
    lastScanDate: '2026-08-13T09:15:00Z',
    coordinates: { x: 5, y: 5, width: 42, height: 40 },
  },
  {
    id: 'field-south',
    farmId: 'farm-1',
    name: 'South Field (Cash Crops & Oilseeds)',
    type: 'field',
    areaAcres: 6.0,
    currentCrop: 'Mustard & Sugarcane',
    healthScore: 94,
    soilMoisture: 58,
    phLevel: 7.1,
    nitrogenLevel: 'Optimal',
    irrigationStatus: 'Scheduled',
    lastScanDate: '2026-08-12T16:00:00Z',
    coordinates: { x: 52, y: 5, width: 43, height: 40 },
  },
  {
    id: 'field-east',
    farmId: 'farm-1',
    name: 'East Field (Vegetables & Spices)',
    type: 'field',
    areaAcres: 4.0,
    currentCrop: 'Tomato, Onion & Garlic',
    healthScore: 78,
    soilMoisture: 52,
    phLevel: 6.9,
    nitrogenLevel: 'Low',
    irrigationStatus: 'Idle',
    lastScanDate: '2026-08-11T11:30:00Z',
    coordinates: { x: 5, y: 50, width: 42, height: 45 },
  },
  {
    id: 'zone-livestock',
    farmId: 'farm-1',
    name: 'Livestock Shed & Feed Unit',
    type: 'livestock',
    areaAcres: 1.5,
    healthScore: 92,
    soilMoisture: 30,
    phLevel: 7.0,
    nitrogenLevel: 'Optimal',
    irrigationStatus: 'Idle',
    lastScanDate: '2026-08-13T08:00:00Z',
    coordinates: { x: 52, y: 50, width: 22, height: 22 },
  },
  {
    id: 'zone-water',
    farmId: 'farm-1',
    name: 'Solar Borewell & Reservoir',
    type: 'water',
    areaAcres: 0.5,
    healthScore: 98,
    soilMoisture: 100,
    phLevel: 7.2,
    nitrogenLevel: 'Optimal',
    irrigationStatus: 'Active',
    lastScanDate: '2026-08-13T10:00:00Z',
    coordinates: { x: 78, y: 50, width: 17, height: 22 },
  },
  {
    id: 'zone-storage',
    farmId: 'farm-1',
    name: 'Grain Silo & Equipment Hub',
    type: 'storage',
    areaAcres: 1.0,
    healthScore: 95,
    soilMoisture: 12,
    phLevel: 7.0,
    nitrogenLevel: 'Optimal',
    irrigationStatus: 'Idle',
    lastScanDate: '2026-08-10T14:00:00Z',
    coordinates: { x: 52, y: 75, width: 43, height: 20 },
  },
];

// 35+ REALISTIC CROPS WITH FULL HEALTH & LIFECYCLE METRICS
export const INITIAL_CROPS: CropItem[] = [
  {
    id: 'crop-1',
    farmId: 'farm-1',
    fieldId: 'field-north',
    name: 'Wheat',
    variety: 'HD-2967 High Yield',
    areaAcres: 4.5,
    sowingDate: '2025-11-10',
    growthStage: 'Harvesting',
    healthScore: 94,
    diseaseRisk: 'low',
    expectedYieldKg: 9500,
    lastScanDate: '2026-08-13T09:15:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-2',
    farmId: 'farm-1',
    fieldId: 'field-north',
    name: 'Basmati Rice (Paddy)',
    variety: 'Pusa Basmati 1121',
    areaAcres: 5.0,
    sowingDate: '2026-06-15',
    growthStage: 'Fruiting',
    healthScore: 91,
    diseaseRisk: 'low',
    expectedYieldKg: 11200,
    lastScanDate: '2026-08-12T16:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-3',
    farmId: 'farm-1',
    fieldId: 'field-south',
    name: 'Mustard (Sarson)',
    variety: 'Pusa Mustard 30',
    areaAcres: 3.5,
    sowingDate: '2025-10-20',
    growthStage: 'Harvesting',
    healthScore: 89,
    diseaseRisk: 'low',
    expectedYieldKg: 4800,
    lastScanDate: '2026-08-11T11:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1508748303406-7bc5a57896ce?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-4',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Tomato',
    variety: 'Pusa Ruby Hybrid',
    areaAcres: 2.5,
    sowingDate: '2026-05-10',
    growthStage: 'Fruiting',
    healthScore: 74,
    diseaseRisk: 'high',
    expectedYieldKg: 4200,
    lastScanDate: '2026-08-13T09:15:00Z',
    activeCondition: 'Early Blight (Alternaria solani)',
    imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-5',
    farmId: 'farm-1',
    fieldId: 'field-south',
    name: 'Potato',
    variety: 'Kufri Jyoti',
    areaAcres: 3.0,
    sowingDate: '2026-06-01',
    growthStage: 'Vegetative',
    healthScore: 92,
    diseaseRisk: 'low',
    expectedYieldKg: 8500,
    lastScanDate: '2026-08-12T16:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-6',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Onion',
    variety: 'N-53 Deep Red',
    areaAcres: 2.0,
    sowingDate: '2026-05-20',
    growthStage: 'Flowering',
    healthScore: 88,
    diseaseRisk: 'low',
    expectedYieldKg: 3100,
    lastScanDate: '2026-08-11T11:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-7',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Chilli',
    variety: 'G-4 Green Hot',
    areaAcres: 1.5,
    sowingDate: '2026-05-15',
    growthStage: 'Fruiting',
    healthScore: 65,
    diseaseRisk: 'high',
    expectedYieldKg: 1800,
    lastScanDate: '2026-08-10T14:45:00Z',
    activeCondition: 'Chilli Leaf Curl Virus',
    imageUrl: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-8',
    farmId: 'farm-1',
    fieldId: 'field-south',
    name: 'Sugarcane',
    variety: 'Co-0238 High Sugar',
    areaAcres: 4.0,
    sowingDate: '2025-03-15',
    growthStage: 'Fruiting',
    healthScore: 95,
    diseaseRisk: 'low',
    expectedYieldKg: 32000,
    lastScanDate: '2026-08-08T10:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-9',
    farmId: 'farm-1',
    fieldId: 'field-south',
    name: 'Cotton',
    variety: 'BT Cotton Bollgard II',
    areaAcres: 3.5,
    sowingDate: '2026-05-01',
    growthStage: 'Flowering',
    healthScore: 86,
    diseaseRisk: 'medium',
    expectedYieldKg: 2800,
    lastScanDate: '2026-08-07T12:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1594904351111-a072f80b1a71?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-10',
    farmId: 'farm-1',
    fieldId: 'field-north',
    name: 'Maize (Corn)',
    variety: 'Rajkumar Hybrid 3355',
    areaAcres: 3.0,
    sowingDate: '2026-06-10',
    growthStage: 'Vegetative',
    healthScore: 93,
    diseaseRisk: 'low',
    expectedYieldKg: 6200,
    lastScanDate: '2026-08-06T15:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-11',
    farmId: 'farm-1',
    fieldId: 'field-north',
    name: 'Chickpea (Chana)',
    variety: 'JG-11 Desi Chana',
    areaAcres: 2.5,
    sowingDate: '2025-11-01',
    growthStage: 'Harvesting',
    healthScore: 90,
    diseaseRisk: 'low',
    expectedYieldKg: 2900,
    lastScanDate: '2026-08-05T09:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-12',
    farmId: 'farm-1',
    fieldId: 'field-south',
    name: 'Soybean',
    variety: 'JS-335 Yellow',
    areaAcres: 3.0,
    sowingDate: '2026-06-20',
    growthStage: 'Vegetative',
    healthScore: 91,
    diseaseRisk: 'low',
    expectedYieldKg: 3600,
    lastScanDate: '2026-08-04T11:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-13',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Garlic',
    variety: 'Yamuna Safed G-282',
    areaAcres: 1.0,
    sowingDate: '2025-10-15',
    growthStage: 'Harvesting',
    healthScore: 96,
    diseaseRisk: 'low',
    expectedYieldKg: 3800,
    lastScanDate: '2026-08-03T14:20:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-14',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Ginger',
    variety: 'Mahima Organic',
    areaAcres: 1.0,
    sowingDate: '2026-05-05',
    growthStage: 'Vegetative',
    healthScore: 89,
    diseaseRisk: 'low',
    expectedYieldKg: 4500,
    lastScanDate: '2026-08-02T10:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-15',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Turmeric (Haldi)',
    variety: 'Pratibha High Curcumin',
    areaAcres: 1.2,
    sowingDate: '2026-05-12',
    growthStage: 'Vegetative',
    healthScore: 94,
    diseaseRisk: 'low',
    expectedYieldKg: 5200,
    lastScanDate: '2026-08-01T16:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-16',
    farmId: 'farm-1',
    fieldId: 'field-north',
    name: 'Green Gram (Moong)',
    variety: 'K-851 Summer Moong',
    areaAcres: 2.0,
    sowingDate: '2026-04-01',
    growthStage: 'Harvesting',
    healthScore: 92,
    diseaseRisk: 'low',
    expectedYieldKg: 1600,
    lastScanDate: '2026-07-28T09:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-17',
    farmId: 'farm-1',
    fieldId: 'field-north',
    name: 'Pearl Millet (Bajra)',
    variety: 'HHB-67 Improved',
    areaAcres: 3.0,
    sowingDate: '2026-07-01',
    growthStage: 'Germination',
    healthScore: 97,
    diseaseRisk: 'low',
    expectedYieldKg: 3800,
    lastScanDate: '2026-07-25T11:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-18',
    farmId: 'farm-1',
    fieldId: 'field-south',
    name: 'Groundnut (Peanut)',
    variety: 'TAG-24 Bold',
    areaAcres: 2.5,
    sowingDate: '2026-06-25',
    growthStage: 'Vegetative',
    healthScore: 88,
    diseaseRisk: 'medium',
    expectedYieldKg: 3200,
    lastScanDate: '2026-07-20T14:10:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1567892999351-4091a18c6395?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-19',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Brinjal (Eggplant)',
    variety: 'Pusa Purple Cluster',
    areaAcres: 1.0,
    sowingDate: '2026-05-18',
    growthStage: 'Fruiting',
    healthScore: 82,
    diseaseRisk: 'medium',
    expectedYieldKg: 2400,
    lastScanDate: '2026-07-18T10:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-20',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Okra (Bhindi)',
    variety: 'Arka Anamika',
    areaAcres: 1.2,
    sowingDate: '2026-05-25',
    growthStage: 'Fruiting',
    healthScore: 90,
    diseaseRisk: 'low',
    expectedYieldKg: 2800,
    lastScanDate: '2026-07-15T15:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-21',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Cabbage',
    variety: 'Golden Acre',
    areaAcres: 1.0,
    sowingDate: '2026-06-10',
    growthStage: 'Vegetative',
    healthScore: 95,
    diseaseRisk: 'low',
    expectedYieldKg: 4100,
    lastScanDate: '2026-07-12T09:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-22',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Cauliflower',
    variety: 'Pusa Snowball K-1',
    areaAcres: 1.0,
    sowingDate: '2026-06-12',
    growthStage: 'Vegetative',
    healthScore: 93,
    diseaseRisk: 'low',
    expectedYieldKg: 3900,
    lastScanDate: '2026-07-10T12:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-23',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Carrot',
    variety: 'Pusa Rudhira Red',
    areaAcres: 0.8,
    sowingDate: '2026-06-05',
    growthStage: 'Vegetative',
    healthScore: 96,
    diseaseRisk: 'low',
    expectedYieldKg: 2600,
    lastScanDate: '2026-07-08T08:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-12f6a67367c8?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-24',
    farmId: 'farm-1',
    fieldId: 'field-north',
    name: 'Sunflower',
    variety: 'KBSH-44 Hybrid',
    areaAcres: 1.5,
    sowingDate: '2026-06-01',
    growthStage: 'Flowering',
    healthScore: 94,
    diseaseRisk: 'low',
    expectedYieldKg: 1900,
    lastScanDate: '2026-07-05T14:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-25',
    farmId: 'farm-1',
    fieldId: 'field-north',
    name: 'Sorghum (Jowar)',
    variety: 'CSV-15 White Grain',
    areaAcres: 2.0,
    sowingDate: '2026-06-15',
    growthStage: 'Vegetative',
    healthScore: 91,
    diseaseRisk: 'low',
    expectedYieldKg: 3100,
    lastScanDate: '2026-07-01T10:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-26',
    farmId: 'farm-1',
    fieldId: 'field-north',
    name: 'Finger Millet (Ragi)',
    variety: 'GPU-28 High Iron',
    areaAcres: 1.5,
    sowingDate: '2026-06-18',
    growthStage: 'Vegetative',
    healthScore: 95,
    diseaseRisk: 'low',
    expectedYieldKg: 2200,
    lastScanDate: '2026-06-28T16:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-27',
    farmId: 'farm-1',
    fieldId: 'field-south',
    name: 'Sesame (Til)',
    variety: 'RT-351 White Sesame',
    areaAcres: 1.0,
    sowingDate: '2026-06-22',
    growthStage: 'Germination',
    healthScore: 98,
    diseaseRisk: 'low',
    expectedYieldKg: 850,
    lastScanDate: '2026-06-25T11:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1508748303406-7bc5a57896ce?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-28',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Mango Orchard',
    variety: 'Alphonso & Dasheri',
    areaAcres: 2.0,
    sowingDate: '2020-07-15',
    growthStage: 'Fruiting',
    healthScore: 96,
    diseaseRisk: 'low',
    expectedYieldKg: 6500,
    lastScanDate: '2026-06-20T13:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-29',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Banana Plantation',
    variety: 'Grand Naine Tissue Culture',
    areaAcres: 1.5,
    sowingDate: '2025-08-10',
    growthStage: 'Fruiting',
    healthScore: 92,
    diseaseRisk: 'low',
    expectedYieldKg: 14000,
    lastScanDate: '2026-06-18T09:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-30',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Papaya',
    variety: 'Red Lady 786 Hybrid',
    areaAcres: 1.0,
    sowingDate: '2025-11-20',
    growthStage: 'Fruiting',
    healthScore: 90,
    diseaseRisk: 'low',
    expectedYieldKg: 9000,
    lastScanDate: '2026-06-15T15:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-31',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Guava (Amrood)',
    variety: 'Allahabad Safeda',
    areaAcres: 1.0,
    sowingDate: '2021-08-10',
    growthStage: 'Fruiting',
    healthScore: 94,
    diseaseRisk: 'low',
    expectedYieldKg: 4800,
    lastScanDate: '2026-06-10T10:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1536511157201-5222b3a628a5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-32',
    farmId: 'farm-1',
    fieldId: 'field-east',
    name: 'Pomegranate (Anar)',
    variety: 'Bhagwa Red Super',
    areaAcres: 1.2,
    sowingDate: '2022-02-15',
    growthStage: 'Fruiting',
    healthScore: 93,
    diseaseRisk: 'low',
    expectedYieldKg: 5100,
    lastScanDate: '2026-06-05T14:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-33',
    farmId: 'farm-1',
    fieldId: 'field-south',
    name: 'Black Gram (Urad)',
    variety: 'PU-31 Resistant',
    areaAcres: 1.5,
    sowingDate: '2026-06-28',
    growthStage: 'Vegetative',
    healthScore: 89,
    diseaseRisk: 'low',
    expectedYieldKg: 1200,
    lastScanDate: '2026-06-01T11:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-34',
    farmId: 'farm-1',
    fieldId: 'field-south',
    name: 'Lentil (Masoor)',
    variety: 'IPL-81 Small Grain',
    areaAcres: 1.5,
    sowingDate: '2025-11-15',
    growthStage: 'Harvesting',
    healthScore: 91,
    diseaseRisk: 'low',
    expectedYieldKg: 1400,
    lastScanDate: '2026-05-25T09:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crop-35',
    farmId: 'farm-1',
    fieldId: 'field-north',
    name: 'Barley (Jau)',
    variety: 'RD-2552 Malt Grade',
    areaAcres: 2.0,
    sowingDate: '2025-11-05',
    growthStage: 'Harvesting',
    healthScore: 95,
    diseaseRisk: 'low',
    expectedYieldKg: 3900,
    lastScanDate: '2026-05-20T16:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
  },
];

export const INITIAL_PROGRESSION: DiseaseProgressionEntry[] = [
  {
    dayLabel: 'Day 1',
    date: '2026-08-01',
    affectedAreaPercent: 7,
    severity: 'low',
    healthScore: 91,
    treatmentApplied: 'None',
    weatherHumidity: 62,
    aiInterpretation: 'Initial subtle brown concentric rings detected on lower foliage.',
  },
  {
    dayLabel: 'Day 4',
    date: '2026-08-05',
    affectedAreaPercent: 12,
    severity: 'moderate',
    healthScore: 84,
    treatmentApplied: 'Neem Oil Spray (15ml/L)',
    weatherHumidity: 68,
    aiInterpretation: 'Lesions expanded into target-board pattern with yellow chlorotic halos.',
  },
  {
    dayLabel: 'Day 8',
    date: '2026-08-09',
    affectedAreaPercent: 18,
    severity: 'moderate',
    healthScore: 78,
    treatmentApplied: 'Organic Trichoderma Bio-fungicide',
    weatherHumidity: 75,
    aiInterpretation: 'Spreading upward to mid-canopy leaves following monsoon rains.',
  },
  {
    dayLabel: 'Day 12',
    date: '2026-08-13',
    affectedAreaPercent: 29,
    severity: 'high',
    healthScore: 74,
    treatmentApplied: 'Pending Copper Oxychloride Spray',
    weatherHumidity: 82,
    aiInterpretation: 'Observed affected leaf area has increased rapidly due to high ambient humidity (82%). Immediate fungicide application required.',
  },
];

// COMPREHENSIVE LIVESTOCK REPOSITORY (COWS, BUFFALOES, GOATS, SHEEP, POULTRY, SWINE)
export const INITIAL_LIVESTOCK: LivestockAnimal[] = [
  {
    id: 'animal-1',
    farmId: 'farm-1',
    tagNumber: 'IND-RJ-101',
    type: 'Cow',
    breed: 'Sahiwal Pure Indigenous',
    ageMonths: 36,
    weightKg: 425,
    healthScore: 94,
    riskLevel: 'low',
    lastVaccinationDate: '2026-06-15',
    nextVaccinationDue: '2026-12-15',
    lastCheckDate: '2026-08-13',
    imageUrl: 'https://images.unsplash.com/photo-1546445317-29f4545f9d52?auto=format&fit=crop&w=600&q=80',
    notes: 'High milk yield (16.5 L/day). Calm temperament. Heat tolerance high.',
  },
  {
    id: 'animal-2',
    farmId: 'farm-1',
    tagNumber: 'IND-RJ-102',
    type: 'Cow',
    breed: 'Gir High Yield',
    ageMonths: 42,
    weightKg: 460,
    healthScore: 96,
    riskLevel: 'low',
    lastVaccinationDate: '2026-05-10',
    nextVaccinationDue: '2026-11-10',
    lastCheckDate: '2026-08-12',
    imageUrl: 'https://images.unsplash.com/photo-1570042707227-2c9ff504b2eb?auto=format&fit=crop&w=600&q=80',
    notes: 'A2 Milk Producer (18 L/day). Excellent body condition score.',
  },
  {
    id: 'animal-3',
    farmId: 'farm-1',
    tagNumber: 'IND-RJ-204',
    type: 'Buffalo',
    breed: 'Murrah Black Gold',
    ageMonths: 48,
    weightKg: 590,
    healthScore: 86,
    riskLevel: 'medium',
    lastVaccinationDate: '2026-02-10',
    nextVaccinationDue: '2026-08-20',
    lastCheckDate: '2026-08-13',
    imageUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?auto=format&fit=crop&w=600&q=80',
    notes: 'Fat content 7.8% (21 L/day). FMD booster vaccination due in 7 days.',
  },
  {
    id: 'animal-4',
    farmId: 'farm-1',
    tagNumber: 'IND-RJ-205',
    type: 'Buffalo',
    breed: 'Nili-Ravi Punjab Breed',
    ageMonths: 38,
    weightKg: 540,
    healthScore: 92,
    riskLevel: 'low',
    lastVaccinationDate: '2026-04-18',
    nextVaccinationDue: '2026-10-18',
    lastCheckDate: '2026-08-11',
    imageUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?auto=format&fit=crop&w=600&q=80',
    notes: 'Wall eyes characteristic of breed. Peak lactation period.',
  },
  {
    id: 'animal-5',
    farmId: 'farm-1',
    tagNumber: 'IND-RJ-309',
    type: 'Goat',
    breed: 'Barbari Dual Purpose',
    ageMonths: 18,
    weightKg: 35,
    healthScore: 95,
    riskLevel: 'low',
    lastVaccinationDate: '2026-05-01',
    nextVaccinationDue: '2026-11-01',
    lastCheckDate: '2026-08-11',
    imageUrl: 'https://images.unsplash.com/photo-1524024973431-2ad916746881?auto=format&fit=crop&w=600&q=80',
    notes: 'Twin kid birth last month. Milk yield 2.2 L/day.',
  },
  {
    id: 'animal-6',
    farmId: 'farm-1',
    tagNumber: 'IND-RJ-310',
    type: 'Goat',
    breed: 'Jamnapari Tall Goat',
    ageMonths: 24,
    weightKg: 52,
    healthScore: 94,
    riskLevel: 'low',
    lastVaccinationDate: '2026-06-01',
    nextVaccinationDue: '2026-12-01',
    lastCheckDate: '2026-08-10',
    imageUrl: 'https://images.unsplash.com/photo-1524024973431-2ad916746881?auto=format&fit=crop&w=600&q=80',
    notes: 'Long convex nose profile. High milk yield (3.1 L/day).',
  },
  {
    id: 'animal-7',
    farmId: 'farm-1',
    tagNumber: 'IND-RJ-402',
    type: 'Sheep',
    breed: 'Marwari Carpet Wool',
    ageMonths: 24,
    weightKg: 48,
    healthScore: 88,
    riskLevel: 'low',
    lastVaccinationDate: '2026-04-12',
    nextVaccinationDue: '2026-10-12',
    lastCheckDate: '2026-08-10',
    imageUrl: 'https://images.unsplash.com/photo-1484557052118-f32bd25b45b5?auto=format&fit=crop&w=600&q=80',
    notes: 'Wool yield 1.8 kg per shearing. Grazing well in pasture.',
  },
  {
    id: 'animal-8',
    farmId: 'farm-1',
    tagNumber: 'IND-RJ-510',
    type: 'Chicken',
    breed: 'Kadaknath Black Poultry (Flock of 50)',
    ageMonths: 8,
    weightKg: 2.4,
    healthScore: 98,
    riskLevel: 'low',
    lastVaccinationDate: '2026-07-01',
    nextVaccinationDue: '2026-10-01',
    lastCheckDate: '2026-08-13',
    imageUrl: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&w=600&q=80',
    notes: 'Medicinal black meat poultry. 42 eggs/day output across flock.',
  },
];

export const INITIAL_ADVISORIES: AdvisoryItem[] = [
  {
    id: 'adv-1',
    farmId: 'farm-1',
    priority: 'CRITICAL',
    category: 'Crop',
    title: 'Tomato Early Blight Pathology Escalation',
    reason: 'Foliage infection expanded to 29% surface coverage due to 82% relative atmospheric humidity.',
    recommendedActions: [
      'Apply Copper Oxychloride 50% WP (2.5g / Liter water) spray immediately across North Field.',
      'Prune lower chlorotic leaves and incinerate outside cultivation boundary.',
      'Transition from overhead flood irrigation to subsurface drip to eliminate foliage dampness.',
    ],
    relatedCropId: 'crop-4',
    createdAt: '2026-08-13T09:20:00Z',
    status: 'active',
  },
  {
    id: 'adv-2',
    farmId: 'farm-1',
    priority: 'HIGH',
    category: 'Crop',
    title: 'Chilli Leaf Curl Virus Vector Control',
    reason: 'Whitefly pest population detected near East Field border threatening green chilli crop.',
    recommendedActions: [
      'Install yellow sticky traps (15 traps per acre) to monitor and catch whiteflies.',
      'Spray Imidacloprid 17.8% SL (0.5ml / Liter water) or Neem Oil 10,000 PPM (5ml/L).',
    ],
    relatedCropId: 'crop-7',
    createdAt: '2026-08-13T07:45:00Z',
    status: 'active',
  },
  {
    id: 'adv-3',
    farmId: 'farm-1',
    priority: 'MEDIUM',
    category: 'Livestock',
    title: 'Murrah Buffalo FMD Booster Reminder',
    reason: 'Tag #IND-RJ-204 due for mandatory Foot & Mouth Disease booster vaccination within 7 days.',
    recommendedActions: [
      'Schedule government vet doctor visit for vaccination.',
      'Isolate animal during booster recovery window.',
    ],
    createdAt: '2026-08-12T14:30:00Z',
    status: 'active',
  },
  {
    id: 'adv-4',
    farmId: 'farm-1',
    priority: 'HIGH',
    category: 'Weather',
    title: 'Paddy Nitrogen Top-Dressing Window',
    reason: 'Rainfall forecast indicates optimal soil moisture in 24 hours for Urea application.',
    recommendedActions: [
      'Broadcast Neem-Coated Urea @ 35 kg/acre on Basmati Paddy Field.',
      'Maintain 2-3 cm standing water depth during application.',
    ],
    relatedCropId: 'crop-2',
    createdAt: '2026-08-11T16:00:00Z',
    status: 'active',
  },
];

export const INITIAL_ALERTS: AlertNotification[] = [
  {
    id: 'alt-1',
    farmId: 'farm-1',
    type: 'Disease',
    severity: 'Critical',
    title: 'Early Blight Outbreak Alert',
    message: 'Tomato canopy infection reached 29%. Apply Copper Fungicide today.',
    timestamp: '2026-08-13T09:16:00Z',
    read: false,
    sourceEvidenceId: 'crop-4',
  },
  {
    id: 'alt-2',
    farmId: 'farm-1',
    type: 'Weather',
    severity: 'Attention',
    title: 'High Humidity Monsoon Alert (85%)',
    message: 'Scattered rainfall expected between 14:00 - 18:00.',
    timestamp: '2026-08-13T06:30:00Z',
    read: false,
  },
  {
    id: 'alt-3',
    farmId: 'farm-1',
    type: 'Livestock',
    severity: 'Information',
    title: 'Morning Fodder & Ration Completed',
    message: 'Livestock Shed morning green fodder delivered.',
    timestamp: '2026-08-13T08:00:00Z',
    read: true,
  },
];

export const INITIAL_TASKS: FarmTask[] = [
  {
    id: 'task-1',
    farmId: 'farm-1',
    title: 'Fungicide Spray on Tomato Field',
    description: 'Spray Copper Oxychloride (2.5g/L) on North Field tomato crop.',
    priority: 'High',
    status: 'Todo',
    dueDate: '2026-08-14',
    assignedTo: 'Farm Owner',
    relatedCropOrAnimal: 'Tomato (Pusa Ruby)',
    reason: 'Early Blight containment',
    createdAt: '2026-08-13T09:25:00Z',
  },
  {
    id: 'task-2',
    farmId: 'farm-1',
    title: 'Urea Top Dressing on Basmati Rice',
    description: 'Broadcast 35kg/acre Neem Coated Urea in Paddy field.',
    priority: 'High',
    status: 'Todo',
    dueDate: '2026-08-15',
    assignedTo: 'Suresh Patel',
    relatedCropOrAnimal: 'Basmati Rice',
    createdAt: '2026-08-13T08:00:00Z',
  },
  {
    id: 'task-3',
    farmId: 'farm-1',
    title: 'Murrah Buffalo FMD Vaccination',
    description: 'Coordinate with Veterinary Officer for Tag #IND-RJ-204.',
    priority: 'Medium',
    status: 'In Progress',
    dueDate: '2026-08-18',
    assignedTo: 'Farm Owner',
    relatedCropOrAnimal: 'Murrah Buffalo',
    createdAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'task-4',
    farmId: 'farm-1',
    title: 'Borewell Solar Panel Dust Cleaning',
    description: 'Wipe down 12 solar panels at water reservoir pump house.',
    priority: 'Low',
    status: 'Completed',
    dueDate: '2026-08-12',
    assignedTo: 'Ramesh Singh',
    relatedCropOrAnimal: 'Solar Borewell',
    createdAt: '2026-08-11T14:00:00Z',
  },
];

export const INITIAL_TIMELINE: TimelineEvent[] = [
  {
    id: 'time-1',
    farmId: 'farm-1',
    timestamp: '2026-08-13T09:15:00Z',
    timeLabel: '09:15 AM',
    title: 'AI Pathology Scan Uploaded',
    description: 'Tomato leaf scan confirmed Early Blight (Alternaria solani) at 94% AI confidence.',
    type: 'scan',
    icon: 'Camera',
    actor: 'Rajesh Kumar',
  },
  {
    id: 'time-2',
    farmId: 'farm-1',
    timestamp: '2026-08-13T09:20:00Z',
    timeLabel: '09:20 AM',
    title: 'Critical Advisory Triggered',
    description: 'AI System issued copper fungicide treatment recommendation for 2.5 acres.',
    type: 'advisory',
    icon: 'AlertTriangle',
    actor: 'AgriVision AI Engine',
  },
  {
    id: 'time-3',
    farmId: 'farm-1',
    timestamp: '2026-08-13T07:30:00Z',
    timeLabel: '07:30 AM',
    title: 'Solar Drip Irrigation Cycle Started',
    description: 'Automated 2-hour drip cycle delivered 14,000 Liters to South Field.',
    type: 'irrigation',
    icon: 'Droplets',
    actor: 'IoT Controller',
  },
  {
    id: 'time-4',
    farmId: 'farm-1',
    timestamp: '2026-08-12T17:45:00Z',
    timeLabel: '05:45 PM',
    title: 'Milk Collection Recorded',
    description: 'Logged 37.5 Liters total daily milk yield from Sahiwal Cows and Murrah Buffaloes.',
    type: 'livestock',
    icon: 'Milk',
    actor: 'Farm Owner',
  },
  {
    id: 'time-5',
    farmId: 'farm-1',
    timestamp: '2026-08-12T11:00:00Z',
    timeLabel: '11:00 AM',
    title: 'Mandi Sale Executed',
    description: 'Sold 18 Quintals Wheat HD-2967 at Jaipur Mandi for ₹2,450 / Quintal.',
    type: 'treatment',
    icon: 'DollarSign',
    actor: 'Jaipur Grain Mandi',
  },
];

export const INITIAL_FEED: FarmFeedPost[] = [
  {
    id: 'feed-1',
    farmId: 'farm-1',
    farmName: 'Rajasthan Green Fields',
    farmerName: 'Rajesh Kumar',
    farmerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    timestamp: '2 hours ago',
    imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=800&q=80',
    category: 'Diseases',
    targetName: 'Tomato - East Field',
    description: 'Scanned lower canopy leaves today. Early Blight concentric rings visible. Applying bio-fungicide this evening.',
    aiAnalysis: {
      condition: 'Early Blight (Alternaria solani)',
      confidence: 94,
      severity: 'Moderate to High',
    },
    likesCount: 24,
    commentsCount: 7,
    userLiked: true,
  },
  {
    id: 'feed-2',
    farmId: 'farm-1',
    farmName: 'Punjab Agro Estate',
    farmerName: 'Harpreet Singh',
    farmerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    timestamp: '5 hours ago',
    imageUrl: 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=800&q=80',
    category: 'Crops',
    targetName: 'Pusa Basmati Rice 1121',
    description: 'Panicle emergence started in 10 acres of Basmati! Standing water depth maintained at 4cm using solar pump.',
    likesCount: 56,
    commentsCount: 14,
    userLiked: false,
  },
  {
    id: 'feed-3',
    farmId: 'farm-1',
    farmName: 'Malwa Dairy & Organic Farm',
    farmerName: 'Shivaji Rao',
    farmerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    timestamp: '1 day ago',
    imageUrl: 'https://images.unsplash.com/photo-1546445317-29f4545f9d52?auto=format&fit=crop&w=800&q=80',
    category: 'Livestock',
    targetName: 'Gir Pure Cow #102',
    description: 'Recorded peak milk yield of 19.2 Liters today after introducing Azolla green fodder in daily ration!',
    likesCount: 89,
    commentsCount: 19,
    userLiked: true,
  },
];

export const INITIAL_MARKETPLACE_ITEMS: MarketplaceItem[] = [
  {
    id: 'mkt-1',
    title: 'Pusa Basmati Rice 1121 Hybrid Seeds (Government Certified)',
    category: 'Seeds',
    price: 1850,
    originalPrice: 2200,
    unit: '10 kg bag',
    sellerName: 'National Seeds Corporation (NSC)',
    sellerRating: 4.9,
    sellerLocation: 'Jaipur, Rajasthan',
    imageUrl: 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=600&q=80',
    description: 'High germination rate (98%), disease resistant to bacterial leaf blight. Produces aromatic extra-long grains.',
    inStock: true,
    allowBargain: true,
    minAcceptablePrice: 1650,
    tag: 'Government Certified',
  },
  {
    id: 'mkt-2',
    title: 'Fast Germinating Hybrid Wheat Seed (HD-3086)',
    category: 'Seeds',
    price: 1450,
    originalPrice: 1700,
    unit: '40 kg bag',
    sellerName: 'IFFCO Kisan Agri Store',
    sellerRating: 4.8,
    sellerLocation: 'Ludhiana, Punjab',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
    description: 'Rust resistant high-yield wheat variety. Tillering potential 12-14 shoots per plant. Maturity 135 days.',
    inStock: true,
    allowBargain: true,
    minAcceptablePrice: 1300,
    tag: 'Fast Germination',
  },
  {
    id: 'mkt-3',
    title: 'Pusa Mustard 30 High-Oil Hybrid Seed',
    category: 'Seeds',
    price: 920,
    originalPrice: 1100,
    unit: '2 kg pack',
    sellerName: 'Rajasthan Seed Corporation',
    sellerRating: 4.7,
    sellerLocation: 'Kota, Rajasthan',
    imageUrl: 'https://images.unsplash.com/photo-1508748303406-7bc5a57896ce?auto=format&fit=crop&w=600&q=80',
    description: '42% oil content variety. Early maturing (110 days). Drought tolerant and aphid resistant.',
    inStock: true,
    allowBargain: true,
    minAcceptablePrice: 820,
    tag: 'High Yield',
  },
  {
    id: 'mkt-4',
    title: 'IFFCO Nano Urea Liquid Fertilizer (500ml)',
    category: 'Fertilizers',
    price: 240,
    originalPrice: 280,
    unit: '500 ml bottle',
    sellerName: 'IFFCO Farmers Hub',
    sellerRating: 4.9,
    sellerLocation: 'New Delhi',
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
    description: 'Replaces 1 bag of conventional granular urea! 80% nitrogen absorption efficiency via foliage spray.',
    inStock: true,
    allowBargain: false,
    tag: 'Organic',
  },
  {
    id: 'mkt-5',
    title: 'NPK 19-19-19 Water Soluble Fertilizer',
    category: 'Fertilizers',
    price: 1150,
    originalPrice: 1350,
    unit: '25 kg bag',
    sellerName: 'KRIBHCO Agro Supply',
    sellerRating: 4.8,
    sellerLocation: 'Udaipur, Rajasthan',
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
    description: 'Balanced crop nutrition for drip irrigation & foliar spray. Enhances root growth and flowering.',
    inStock: true,
    allowBargain: true,
    minAcceptablePrice: 1020,
    tag: 'High Yield',
  },
  {
    id: 'mkt-6',
    title: 'Copper Oxychloride 50% WP Bio-Fungicide',
    category: 'Protection',
    price: 480,
    originalPrice: 560,
    unit: '500 g pack',
    sellerName: 'Bayer CropScience Hub',
    sellerRating: 4.9,
    sellerLocation: 'Indore, Madhya Pradesh',
    imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=600&q=80',
    description: 'Broad-spectrum protective copper fungicide for Early/Late Blight in Tomatoes & Potatoes.',
    inStock: true,
    allowBargain: true,
    minAcceptablePrice: 420,
    tag: 'High Yield',
  },
  {
    id: 'mkt-7',
    title: 'AgriVision 5 HP Solar Submersible Borewell Pump System',
    category: 'Machinery',
    price: 84500,
    originalPrice: 98000,
    unit: 'Full Set with Solar Panels',
    sellerName: 'TATA Solar Power Systems',
    sellerRating: 4.95,
    sellerLocation: 'Ahmedabad, Gujarat',
    imageUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=600&q=80',
    description: 'Zero electricity bill pump with 8 TATA 335W Monocrystalline solar panels. 5-year warranty + subsidy support.',
    inStock: true,
    allowBargain: true,
    minAcceptablePrice: 78000,
    tag: 'Government Certified',
  },
  {
    id: 'mkt-8',
    title: 'Murrah High-Yield Black Buffalo (In Milk 18L/day)',
    category: 'Livestock',
    price: 92000,
    originalPrice: 105000,
    unit: '1 Animal (Second Calving)',
    sellerName: 'Rohtak Murrah Breeding Farm',
    sellerRating: 4.9,
    sellerLocation: 'Rohtak, Haryana',
    imageUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?auto=format&fit=crop&w=600&q=80',
    description: 'Pure Murrah breed with veterinary health certificate, FMD vaccinated, calm temperament.',
    inStock: true,
    allowBargain: true,
    minAcceptablePrice: 85000,
    tag: 'High Yield',
  },
  {
    id: 'mkt-9',
    title: 'High-Protein Cattle Feed Mash (20% Protein)',
    category: 'Feed',
    price: 1280,
    originalPrice: 1450,
    unit: '50 kg bag',
    sellerName: 'Amul Dairy Cattle Feed Depot',
    sellerRating: 4.85,
    sellerLocation: 'Anand, Gujarat',
    imageUrl: 'https://images.unsplash.com/photo-1546445317-29f4545f9d52?auto=format&fit=crop&w=600&q=80',
    description: 'Enriched with bypass fat, calcium, and chelated minerals. Increases milk fat & solids-not-fat (SNF).',
    inStock: true,
    allowBargain: true,
    minAcceptablePrice: 1150,
    tag: 'High Yield',
  },
];

export const INITIAL_MANDI_PRICES: MandiPriceItem[] = [
  {
    id: 'mndi-1',
    commodity: 'Wheat (Gehun)',
    variety: 'HD-2967 Sharbati',
    mandiName: 'Jaipur Grain Mandi',
    state: 'Rajasthan',
    minPrice: 2380,
    maxPrice: 2520,
    modalPrice: 2450,
    trend: 'up',
    changePercent: 2.4,
    date: '2026-08-14',
  },
  {
    id: 'mndi-2',
    commodity: 'Paddy / Basmati Rice',
    variety: 'Pusa Basmati 1121',
    mandiName: 'Khanna Mandi',
    state: 'Punjab',
    minPrice: 3850,
    maxPrice: 4200,
    modalPrice: 4050,
    trend: 'up',
    changePercent: 3.1,
    date: '2026-08-14',
  },
  {
    id: 'mndi-3',
    commodity: 'Mustard (Sarson)',
    variety: 'Black Bold',
    mandiName: 'Bharatpur Mandi',
    state: 'Rajasthan',
    minPrice: 5400,
    maxPrice: 5750,
    modalPrice: 5620,
    trend: 'up',
    changePercent: 1.8,
    date: '2026-08-14',
  },
  {
    id: 'mndi-4',
    commodity: 'Soybean',
    variety: 'Yellow JS-335',
    mandiName: 'Indore Mandi',
    state: 'Madhya Pradesh',
    minPrice: 4500,
    maxPrice: 4850,
    modalPrice: 4720,
    trend: 'stable',
    changePercent: 0.2,
    date: '2026-08-14',
  },
  {
    id: 'mndi-5',
    commodity: 'Tomato',
    variety: 'Hybrid Red',
    mandiName: 'Azadpur Mandi',
    state: 'Delhi',
    minPrice: 1800,
    maxPrice: 2400,
    modalPrice: 2150,
    trend: 'down',
    changePercent: -4.5,
    date: '2026-08-14',
  },
  {
    id: 'mndi-6',
    commodity: 'Cotton (Kapas)',
    variety: 'Medium Staple',
    mandiName: 'Rajkot Mandi',
    state: 'Gujarat',
    minPrice: 6800,
    maxPrice: 7350,
    modalPrice: 7100,
    trend: 'up',
    changePercent: 1.5,
    date: '2026-08-14',
  },
];

export const INITIAL_TREATMENT_CHARTS: TreatmentScheduleItem[] = [
  {
    id: 'trt-1',
    cropName: 'Tomato',
    diseaseName: 'Early Blight (Alternaria solani)',
    activeIngredient: 'Copper Oxychloride 50% WP',
    brandNames: ['Blitox 50', 'Fytolan', 'Kocide 3000'],
    dosagePerAcre: '500g diluted in 200 Liters clean water',
    applicationMethod: 'Foliar spray covering upper and lower leaf canopy',
    sprayingIntervalDays: 7,
    preHarvestIntervalDays: 3,
    safetyLevel: 'Moderate Precaution',
  },
  {
    id: 'trt-2',
    cropName: 'Chilli',
    diseaseName: 'Chilli Leaf Curl Virus (Whitefly Vector)',
    activeIngredient: 'Imidacloprid 17.8% SL + Neem Oil',
    brandNames: ['Confidor', 'Victor', 'Neemazal 10000 PPM'],
    dosagePerAcre: '100ml Imidacloprid + 1L Neem Oil in 200L water',
    applicationMethod: 'Foliar spray during early morning before whitefly flight',
    sprayingIntervalDays: 10,
    preHarvestIntervalDays: 7,
    safetyLevel: 'Moderate Precaution',
  },
  {
    id: 'trt-3',
    cropName: 'Potato',
    diseaseName: 'Late Blight (Phytophthora infestans)',
    activeIngredient: 'Mancozeb 75% WP or Cymoxanil + Mancozeb',
    brandNames: ['Indofil M-45', 'Curzate M8', 'Ridomil Gold'],
    dosagePerAcre: '600g in 200 Liters water',
    applicationMethod: 'High pressure knapsack spray at first lesion sight',
    sprayingIntervalDays: 5,
    preHarvestIntervalDays: 7,
    safetyLevel: 'Strict Safety Kit Required',
  },
];

export const INITIAL_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'post-1',
    farmerName: 'Ramesh Patel',
    villageState: 'Sanganer, Rajasthan',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    category: 'Crop Pathology',
    title: 'Successful Control of Early Blight in Tomato using Neem + Trichoderma!',
    content: 'Brothers, my 3 acre tomato crop had severe yellow leaf spots last week. Following AgriVision AI recommendation, I sprayed Trichoderma bio-fungicide mixed with neem oil. In 4 days, new leaves came out completely green!',
    imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=600&q=80',
    likesCount: 38,
    commentsCount: 12,
    userLiked: true,
    timestamp: '3 hours ago',
    verifiedSolution: true,
  },
  {
    id: 'post-2',
    farmerName: 'Gurpreet Singh',
    villageState: 'Bhatinda, Punjab',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    category: 'Live Mandi Price',
    title: 'Khanna Mandi Paddy Rate Updated Today (₹4,080 / Quintal)',
    content: 'Pusa 1121 Basmati prices increased by ₹120 per quintal today in Khanna Mandi due to strong exporter demand. Hold your stock if you can wait another week!',
    likesCount: 52,
    commentsCount: 19,
    userLiked: false,
    timestamp: '5 hours ago',
  },
  {
    id: 'post-3',
    farmerName: 'Kisan Balram',
    villageState: 'Indore, MP',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    category: 'Organic Farming',
    title: 'Jeevamrut Preparation Formula for Wheat & Mustard Soil Health',
    content: 'Mix 10kg desi cow dung, 10L desi cow urine, 2kg jaggery, 2kg besan in 200L water. Ferment for 7 days. Apply via drip irrigation for 30% yield boost without chemical fertilizer!',
    likesCount: 74,
    commentsCount: 23,
    userLiked: true,
    verifiedSolution: true,
    timestamp: '1 day ago',
  },
];

export const INITIAL_SUBSCRIPTION: UserSubscription = {
  plan: 'Professional',
  status: 'active',
  scansUsedThisMonth: 18,
  scansLimit: 500,
  aiChatsUsedThisMonth: 42,
  aiChatsLimit: 2000,
  renewalDate: '2026-09-01',
};
